import Logo from './Frame.svg';
import Logo1 from './BackButton.svg';
import Penyakit from './penyakit.svg';
import Hama from './hama.svg';
import Pupuk from './pupuk.svg';
import Seed from './seed.svg';
import bg from './Group 11.svg';
import Pl from './pl.svg';
import Titik from './titik.svg';
export {Logo, Logo1, Penyakit, Hama, Pupuk, Seed, bg, Pl, Titik};
